-- 코드를 입력하세요
-- 대여시작일을 기준으로 8,9,10 월에 대해서만 
-- Month를 (Month함수로 먼저 가져오기 )
WITH RENTAL_FILTERED AS (
    SELECT
        CAR_ID,
        MONTH(START_DATE) AS MONTH
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
),

CAR_OVER_5 AS (
    SELECT
        CAR_ID
    FROM
        RENTAL_FILTERED
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5
)

SELECT
    R.MONTH,
    R.CAR_ID,
    COUNT(*) AS RECORDS
FROM
    RENTAL_FILTERED R
JOIN
    CAR_OVER_5 C ON R.CAR_ID = C.CAR_ID
GROUP BY
    R.MONTH, R.CAR_ID
ORDER BY
    R.MONTH ASC,
    R.CAR_ID DESC;